name: Docker worlflow

on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
       - name: Check out code
         uses: actions/checkout@v2
       - name: Log in to Docker Hub
         uses: docker/login-action@v2.1.0
         with:
           username: ${{ secrets.DOCKERHUB_NAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }} 
